---
spring:
  application:
    name: Spring Batch Multi Datasource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch-datasource:
    initialize-schema: always
    jdbc-url: jdbc:h2:mem:springbatch
    driver-class-name: org.h2.Driver
    username: sa
    password:
  input-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/employee
    driver-class-name: org.postgresql.Driver
    username: sa
    password:
  output-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/employee
    driver-class-name: org.postgresql.Driver
    username: sa
    password:

  batch:
    job:
      enabled: false

command:
  line:
    runner:
      enabled: true
